name: Continuous Integration

env:
  ROCKSDB_VERSION: v8.10.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: build rocksdb dependency
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/install-rocksdb.sh
      - name: run tests
        run: make test
